version: '3'
services:
  spring:
    build: .
    environment:
      MYSQL_HOST: mysql_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    expose:
      - "8080"
    ports:
      - 8080:8080

  mysql_db:
    image: mysql:8.0.27
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d/:ro
    expose:
      - "3306"
    ports:
      - 3305:3306

volumes:
  data: